
#include "/urs_render/feature/post_processing/dual_kawase_blur/ursDualKawaseBlur_Common.ush"

Texture2D       m_srcTex;
SamplerState    m_srcTexSampler;

void PS_main(
        noperspective float4 UVAndScreenPos : TEXCOORD0
        , out float4 oColor : SV_Target0
    )   
{
    float2 uv = UVAndScreenPos.xy;

    float4 srcColor = m_srcTex.Sample(m_srcTexSampler, uv);

    oColor.rgba = srcColor.rgba;
}
